pipeline {
    agent any

    stages {
        stage("build") {
            tools {
               jdk "jdk-1.8.101"
            }
            steps {
                echo "build stage..."
                dir("CICD"){
                    sh "ls -al"
                    sh "./mvnw clean install -DskipTests"
                }
            }
        }

        stage("test") {
            tools {
                jdk "jdk-1.8.101"
            }
            steps {
                echo "build stage..."
                dir("CICD"){
                    sh "ls -al"
                    sh "./mvnw test"
                }
            }
        }

        stage("deploy") {
            steps {
                echo "build stage..."
            }
        }
    }
}