pipeline {
    agent any

    stages {
        stage("build") {
            steps {
                echo "build stage..."
                script {
                    pwd
                }
            }
        }

        stage("test") {
            steps {
                echo "build stage..."
            }
        }

        stage("deploy") {
            steps {
                echo "build stage..."
            }
        }
    }
}