pipeline {
    agent {
        docker {
          image 'openjdk:18.0.1.1-jdk'
          args '-p 3000:3000'
        }
    }

    stages {
        stage("build") {
            steps {
                sh 'java -version'
                echo "build stage..."
                dir("CICD"){
                    sh "java -version"
                    sh "./mvnw clean install -DskipTests"
                }
            }
        }

        stage("test") {
            steps {
                sh 'java -version'
                echo "build stage..."
                dir("CICD"){
                    sh "ls -al"
                    sh "./mvnw test"
                }
            }
        }

        stage("deploy") {
            steps {
                echo "build stage..."
            }
        }
    }
}